spring:
  application:
    name: jfk-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: kratos
            uri: lb://kratos
            predicates:
              - Path=/api/kratos/**
          - id: bifrost
            uri: lb://bifrost
            predicates:
              - Path=/api/bifrost/**