spring:
  data:
    mongodb:
      uri: mongodb+srv://${MONGO_ATLAS_USERNAME}:${MONGO_ATLAS_PASSWORD}@${MONGO_ATLAS_CLUSTER_CONNECTION_STRING}
      authentication-database: admin
      database: hydra-db