
spring:
  data:
    redis:
      client-name: hydra
      host: localhost
      port: 6379
    mongodb:
      uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/${DB_NAME}?authSource=admin
  cloud:
    vault:
      authentication: approle
      app-role:
        role-id: ${ROLE_ID}
        secret-id: ${SECRET_ID}
      uri: https://vault-dev.eu-west-1.heimdallauth.com
server:
  port: 0
