spring:
  application:
    name: hydra
  security:
    user:
      name: admin
      password: admin

  cloud:
    consul:
      discovery:
        health-check-path: /api/hydra/actuator/health
server:
  servlet:
    context-path: /api/hydra
heimdall:
  hydra:
    domain-name: heimdallauth.com
    deployment-name: purpleid
    protocol: https