server:
  port: 0

spring:
  data:
    mongodb:
      uri: ${MONGO_URI}
    redis:
      host: localhost
      port: 6379
      database: 0
  cloud:
    config:
      enabled: false
    discovery:
      enabled: true
    consul:
      port: 8500
      host: localhost
