server:
  port: 0

spring:
  data:
    mongodb:
      uri: ${MONGO_URI}
  cloud:
    config:
      enabled: false
    discovery:
      enabled: true
    consul:
      port: 8500
      host: localhost
    vault:
      enabled: true
      host: vault-dev.eu-west-1.heimdallauth.com
      authentication: approle
      app-role:
        app-role-path: approle
        role-id: ${VAULT_ROLE_ID}
        secret-id: ${VAULT_SECRET_ID}
      port: 443