server:
  port: 0
spring:
  cloud:
    config:
      enabled: false
    discovery:
      enabled: true
    consul:
      port: 8500
      host: localhost
resilience4j:
  retry:
    instances:
      mongoInitRetry:
        max-attempts: 5
        wait-duration: 10s
        exponential-backoff-multiplier: 2
        fail-after-max-attempts: true
        enable-exponential-backoff: true
        retry-exceptions:
          - java.lang.Exception