server:
  port: 0
spring:
  cloud:
    config:
      enabled: false
    discovery:
      enabled: true
    consul:
      port: 8500
      host: localhost
    vault:
      enabled: true
      host: vault-dev.eu-west-1.heimdallauth.com
      authentication: approle
      app-role:
        app-role-path: approle
        role-id: ${VAULT_ROLE_ID}
        secret-id: ${VAULT_SECRET_ID}
      port: 443
resilience4j:
  retry:
    instances:
      mongoInitRetry:
        initial-wait-time: 15s
        max-attempts: 5
        wait-duration: 10s
        exponential-backoff-multiplier: 2
        fail-after-max-attempts: true
        enable-exponential-backoff: true
        retry-exceptions:
          - org.springframework.data.mongodb.UncategorizedMongoDbException
          - com.mongodb.MongoException