name: Docker Kratos Image CI

on:
  push:
    tags:
      - 'v*'
permissions:
  contents: read
  pull-requests: write

jobs:
  java-builder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '21'
      - name: Cache Gradle Packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build with Gradle
        run: ./gradlew clean build -x test
      - name: Upload artifacts to Github
        uses: actions/upload-artifact@v4
        with:
          name: artifacts.zip
          path: |
            jfk-gateway/build/libs/*.jar

  docker-builder:
    runs-on: ubuntu-latest
    needs: java-builder
    strategy:
      matrix:
        image: [jfk-gateway]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Echo for Debugging
        run: echo ${{ matrix.image }}
      - name: Download artifacts from Github
        uses: actions/download-artifact@v4
        with:
          name: artifacts.zip
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
            username: ${{secrets.DOCKERHUB_USERNAME}}
            password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64,linux/arm64
      - name: Docker Metadata Generation
        uses: docker/metadata-action@v5
        id: docker-metadata-${{ matrix.image}}
        with:
          images: heimdallauth/${{ matrix.image}}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      - name: Build and push Docker image for ${{matrix.image}}
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.docker-metadata-jfk-gateway.outputs.tags }}
          push: true
          context: ./${{ matrix.image }}/