name: Prepare Release Branches

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number for the release'
        required: true

jobs:
  create-branches:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

#      - name: Create release branch
#        run: |
#          git config --global user.name 'github-actions[bot]'
#          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
#          git checkout -b release/${{ github.event.inputs.version }}
#          git push origin release/${{ github.event.inputs.version }}

      - name: Create release-candidate branch
        run: |
          git checkout -b release-candidate/${{ github.event.inputs.version }}
          git push origin release-candidate/${{ github.event.inputs.version }}